### PR TITLE
added epoch functions

### PR DESCRIPTION
**Pull request by bmoore-msft**
Always seem to have a problem with code diff on this file... here are the changes/additions:

```json
        {
            "description": "Converts an epoch time integer value to an ISO8601 dateTime string value.",
            "expectedUsage": "dateTimeFromEpoch(epochTime)",
            "maximumArguments": 1,
            "minimumArguments": 1,
            "name": "dateTimeFromEpoch"
        },
        {
            "description": "Converts an ISO8601 dateTime string to an epoch time integer value.",
            "expectedUsage": "dateTimeToEpoch(dateTime)",
            "maximumArguments": 1,
            "minimumArguments": 1,
            "name": "dateTimeToEpoch"
        },
```

These are not in docs yet...  (or bicep)

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
@bmoore-msft What editor are you using?  Apparently it's sorting all the property names.

**Comment by bmoore-msft** [comment]
VS Code

**Comment by bmoore-msft** [comment]
Ok, for some reason, when I press CTRL+S in VS Code to save the file, it sorts first and then saves...  It doesn't do this for other repos in VS code, just this one.

**Comment by StephenWeatherford** [comment]
Weird, thanks.  My guess is an extension - prettier, maybe? 

NOTE: You can skip the formatting on save in vscode by using the command palette:
image

**Comment by bmoore-msft** [comment]
it is weird - only does it on this repo... not on any of the others...

**Comment by bmoore-msft** [comment]
Here's why: https://github.com/microsoft/vscode-azurearmtools/blob/main/.vscode/settings.json#L2

**Comment by StephenWeatherford** [comment]
That doesn't explain why sorting is part of formatting. That's not standard.

**Comment by bmoore-msft** [comment]
ok, you're right... I had some odd-ball extension installed (I won't name it) that seemed to want to sort only on this repo for some reason.  It's gone now...

**Comment by StephenWeatherford** [comment]
@bmoore-msft Released in https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.7 on 5/11.

**Pull request merged**
