### PR TITLE
Improve description for uniqueString

### PR DESCRIPTION
**Pull request by StephenWeatherford**
After reading the existing description, I had to look it up to understand how to use.

image
image

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
I'm thinking of adding more info like this (probably not as much for most) for others as well.

**Comment by bmoore-msft** [comment]
@mumian - should be able to help...

**Comment by StephenWeatherford** [comment]
@bmoore-msft This comes straight from the docs, so the text doesn't really need reviewing, just more whether you like the longer format.

**Comment by StephenWeatherford** [comment]
ping

**Comment by StephenWeatherford** [comment]
Thanks!

**Pull request merged**
