### PR TITLE
Use dotnet 3.0.3, support TLS 2/3

### PR DESCRIPTION
**Pull request by StephenWeatherford**
The first commit updates the install scripts to the latest version, although it's mostly whitespace changes.  It also uses 3.0.3 instead of 3.0.2
The second commit attempts to add the TLS 2/3 fix from https://github.com/microsoft/vscode-azurearmtools/issues/598#issuecomment-614855482 and https://github.com/microsoft/vscode-azurearmtools/issues/598#issuecomment-614708618

### CODE REVIEW

**Comment by sfoslund** [comment]
Adding @bozturkMSFT and @donJoseLuis as reviewers, as they own the install script. 

I don't know enough in this area to know if this is a safe change to make given [similar changes to the install script](https://github.com/dotnet/website/pull/1877) have been backed out.

**Comment by bozturkMSFT** [comment]
> Edit: I got come more context on this issue and it sounds like it's safe to set TLS before the script, but not inside of it. I have a draft PR for this change in [dotnet/vscode-dotnet-runtime#60](https://github.com/dotnet/vscode-dotnet-runtime/pull/60)

@sfoslund Can you give more context on this? Why is it safe to set it before but not inside?

**Comment by sfoslund** [comment]
@mmitche can you give an explanation on setting TLS before invoking the script vs during?

**Comment by StephenWeatherford** [comment]
Superseded.

**Pull request closed without merging**
