### PR TITLE
Fix typo in UserFunctions.test.ts

### PR DESCRIPTION
**Pull request by eltociear**
availabe -> available

### CODE REVIEW

**Review by StephenWeatherford — APPROVED** [review]

**Comment by StephenWeatherford** [comment]
The suite failure is not related to this change (obviously :-)), I will take care of it, thanks!

**Comment by eltociear** [comment]
@StephenWeatherford Thank you for letting me know! I got it.

**Comment by StephenWeatherford** [comment]
@eltociear Could you sync up to latest changes and push again?  Thanks.

**Comment by eltociear** [comment]
@StephenWeatherford It corresponded. Is this okay?

**Comment by StephenWeatherford** [comment]
Perfect, thanks!

**Comment by eltociear** [comment]
@StephenWeatherford Yes! Thx!!

**Pull request merged**
