### PR TITLE
Use latest schema version for ARM Template parameter file

### PR DESCRIPTION
**Pull request by wilfriedwoivre**
Schema : https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-04-01/deploymentParameters.json

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
@neilpeterson

**Comment by neilpeterson** [comment]
Yep this looks correct and also aligns with the tools snippet.

https://github.com/microsoft/vscode-azurearmtools/blob/master/assets/jsonsnippets.jsonc#L66

Thanks @wilfriedwoivre!

**Comment by StephenWeatherford** [comment]
Shipping in 0.10.0 on Monday

**Comment by StephenWeatherford** [comment]
Shipped yesterday

**Pull request merged**
